import { Actor, log } from 'apify';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {
    extractVideoId,
    canonicalWatchUrl,
    normalizePreferredLanguage,
    parseVtt,
    dedupeSegments,
    buildTranscriptText,
    normalizeBlockedReason,
    sanitizeCommand,
    parseMetadataLine,
} from './utils.js';

const execFileAsync = promisify(execFile);

// Prepended to every yt-dlp invocation
const YT_DLP_BASE_ARGS = ['--no-playlist', '--socket-timeout', '30'];

async function runYtDlp(args, { proxyUrl, timeoutMs, debug, proxyInjected }) {
    const finalArgs = [...YT_DLP_BASE_ARGS, ...args];
    if (proxyUrl) finalArgs.push('--proxy', proxyUrl);
    if (debug) {
        const sanitized = sanitizeCommand(finalArgs);
        log.info(`yt-dlp cmd: yt-dlp ${sanitized.join(' ')}`);
        log.info(`proxyInjected=${proxyInjected}`);
    }
    try {
        const { stdout, stderr } = await execFileAsync('yt-dlp', finalArgs, {
            timeout: timeoutMs,
            maxBuffer: 10 * 1024 * 1024,
        });
        return { stdout, stderr };
    } catch (err) {
        const stderr = err?.stderr || '';
        if (debug && stderr) {
            const lines = stderr.split(/\r?\n/).slice(0, 15).join('\n');
            log.info(`yt-dlp stderr (first 15 lines):\n${lines}`);
        }
        throw err;
    }
}

async function downloadSubtitles({ url, outputTemplate, preferredLanguage, autoGenerated, proxyUrl, timeoutMs, debug, proxyInjected }) {
    const args = [
        autoGenerated ? '--write-auto-sub' : '--write-sub',
        '--skip-download',
        '--sub-format', 'vtt',
        '--output', outputTemplate,
    ];
    if (preferredLanguage?.length) {
        args.push('--sub-langs', preferredLanguage.join(','));
    }
    args.push(url);
    return runYtDlp(args, { proxyUrl, timeoutMs, debug, proxyInjected });
}

async function findVttFile(dir, outputPrefix) {
    const files = await fs.readdir(dir);
    const vtt = files.find((f) => f.startsWith(outputPrefix) && f.endsWith('.vtt')) || null;
    return vtt ? path.join(dir, vtt) : null;
}

async function loadVttAndParse(filePath, { removeBrackets }) {
    const content = await fs.readFile(filePath, 'utf-8');
    return parseVtt(content, { removeBrackets });
}

async function getProxyUrl(mode) {
    if (mode === 'off') return null;
    try {
        if (mode === 'residential') {
            const cfg = await Actor.createProxyConfiguration({ groups: ['RESIDENTIAL'] });
            return cfg?.newUrl();
        }
        const cfg = await Actor.createProxyConfiguration();
        return cfg?.newUrl();
    } catch {
        return null;
    }
}

async function fetchMetadata(url, opts) {
    try {
        const { stdout } = await runYtDlp(
            ['--skip-download', '--print', '%(title)s\t%(channel)s\t%(duration)s\t%(upload_date)s', url],
            opts,
        );
        return parseMetadataLine(stdout);
    } catch {
        return { title: null, channelName: null, durationSec: null, uploadDate: null };
    }
}

async function processVideo(rawUrl, { cacheStore, outputMode, removeBrackets, joinWith, proxyMode, timeoutMs, maxRetries, saveVttToKV, debug, languagePrefs }) {
    const videoId = extractVideoId(rawUrl || '');
    if (!videoId) {
        await Actor.pushData({ status: 'INVALID_URL', videoUrl: rawUrl, reason: 'Invalid or unsupported YouTube URL' });
        return;
    }

    const canonicalUrl = canonicalWatchUrl(videoId);
    const requestedLangKey = languagePrefs?.[0] || 'default';
    const cacheKey = `yt:${videoId}:${requestedLangKey}`;
    const requestedLanguage = languagePrefs?.[0] || null;

    const cached = await cacheStore.getValue(cacheKey);
    if (cached) {
        await Actor.pushData({ ...cached, cacheHit: true, cacheKey });
        return;
    }

    const attempts = [];
    if (proxyMode === 'auto') attempts.push('datacenter', 'residential');
    else if (proxyMode === 'off') attempts.push('off');
    else attempts.push(proxyMode);

    const hasProxyAuth = Boolean(process.env.APIFY_TOKEN || process.env.APIFY_PROXY_PASSWORD);
    if ((proxyMode === 'datacenter' || proxyMode === 'residential') && !hasProxyAuth) {
        await Actor.pushData({
            status: 'ERROR',
            reason: 'Proxy mode requires APIFY_TOKEN or APIFY_PROXY_PASSWORD',
            videoUrl: canonicalUrl,
            videoId,
            requestedLanguage,
            selectedLanguage: null,
            languageFallback: false,
            subtitleType: 'none',
            source: 'none',
            cacheHit: false,
            cacheKey,
            proxyAttempted: [],
        });
        return;
    }

    const proxyAttempted = [];
    let lastError = null;
    let blockedReason = null;
    // Preserve any partial metadata across attempts for richer error output
    let bestTitle = null;
    let bestChannelName = null;

    const tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'yt-tx-'));

    try {
        for (const [modeIdx, mode] of attempts.entries()) {
            const proxyUrl = await getProxyUrl(mode);
            const proxyInjected = Boolean(proxyUrl);
            if (mode !== 'off') proxyAttempted.push(mode);

            for (let attempt = 0; attempt < Math.max(1, maxRetries); attempt++) {
                // Unique subdirectory per attempt — prevents stale VTT from a previous attempt
                // being found by findVttFile if this attempt's download fails silently.
                const attemptDir = path.join(tempDir, `${modeIdx}_${attempt}`);
                await fs.mkdir(attemptDir, { recursive: true });
                const outputTemplate = path.join(attemptDir, 'transcript');

                // Jitter delay after the very first attempt to reduce rate-limit risk
                if (modeIdx > 0 || attempt > 0) {
                    await Actor.sleep(Math.floor(500 + Math.random() * 1000));
                }

                // All per-attempt state is declared here so nothing bleeds across retries
                let isAutoGenerated = false;
                let usedLanguage = null;
                const warnings = [];
                const langToUse = languagePrefs.length ? languagePrefs : null;

                try {
                    let vttPath = null;
                    let subtitleType = 'manual';
                    let source = 'yt-dlp-manual';
                    let lastDlStderr = '';

                    // Try manual subtitles first
                    try {
                        const dl = await downloadSubtitles({
                            url: canonicalUrl, outputTemplate,
                            preferredLanguage: langToUse, autoGenerated: false,
                            proxyUrl, timeoutMs, debug, proxyInjected,
                        });
                        lastDlStderr = dl.stderr || '';
                        vttPath = await findVttFile(attemptDir, 'transcript');
                    } catch (dlErr) {
                        // yt-dlp exited non-zero — check stderr for rate-limit / block signals
                        lastDlStderr = dlErr?.stderr || '';
                        const blockR = normalizeBlockedReason(lastDlStderr || dlErr?.message || '');
                        if (blockR !== 'unknown') throw new Error(`BLOCKED:${blockR}`);
                        throw dlErr;
                    }

                    if (!vttPath) {
                        // No manual subs — fall back to auto-generated captions
                        subtitleType = 'auto';
                        source = 'yt-dlp-auto';
                        isAutoGenerated = true;
                        try {
                            const dl = await downloadSubtitles({
                                url: canonicalUrl, outputTemplate,
                                preferredLanguage: langToUse, autoGenerated: true,
                                proxyUrl, timeoutMs, debug, proxyInjected,
                            });
                            lastDlStderr = dl.stderr || '';
                            vttPath = await findVttFile(attemptDir, 'transcript');
                        } catch (dlErr) {
                            lastDlStderr = dlErr?.stderr || '';
                            const blockR = normalizeBlockedReason(lastDlStderr || dlErr?.message || '');
                            if (blockR !== 'unknown') throw new Error(`BLOCKED:${blockR}`);
                            throw dlErr;
                        }
                    }

                    if (!vttPath) {
                        // yt-dlp succeeded (exit 0) but wrote no file — either genuinely no
                        // subtitles or a soft block where yt-dlp returns empty output.
                        const blockR = normalizeBlockedReason(lastDlStderr);
                        if (blockR !== 'unknown') throw new Error(`BLOCKED:${blockR}`);
                        throw new Error('NO_TRANSCRIPT');
                    }

                    const segments = dedupeSegments(await loadVttAndParse(vttPath, { removeBrackets }));
                    const transcriptText = buildTranscriptText(segments, joinWith);

                    // Derive language from filename: transcript.<lang>.vtt
                    const fname = path.basename(vttPath);
                    const parts = fname.split('.');
                    if (parts.length >= 3) usedLanguage = parts[parts.length - 2];

                    // Warn if the track we got doesn't match what was requested
                    if (langToUse?.length && usedLanguage && !langToUse.some((l) => usedLanguage === l || usedLanguage.startsWith(`${l}-`))) {
                        warnings.push('Preferred language not available; using fallback track.');
                    }

                    // Fetch all metadata in a single yt-dlp call (was 3 separate calls)
                    const meta = await fetchMetadata(canonicalUrl, { proxyUrl, timeoutMs, debug, proxyInjected });
                    bestTitle = meta.title ?? bestTitle;
                    bestChannelName = meta.channelName ?? bestChannelName;

                    const languageFallback = warnings.length > 0;
                    const output = {
                        status: 'SUCCESS',
                        videoUrl: canonicalUrl,
                        videoId,
                        transcriptText,
                        requestedLanguage,
                        selectedLanguage: usedLanguage || null,
                        languageFallback,
                        subtitleType,
                        source,
                        isAutoGenerated,
                        warnings,
                        cacheHit: false,
                        cacheKey,
                        proxyAttempted: [...proxyAttempted],
                    };

                    if (bestTitle) output.title = bestTitle;
                    if (bestChannelName) output.channelName = bestChannelName;
                    if (meta.durationSec != null) output.durationSec = meta.durationSec;
                    if (meta.uploadDate) output.uploadDate = meta.uploadDate;
                    if (outputMode === 'text_and_segments') output.segments = segments;

                    if (saveVttToKV) {
                        const vttContent = await fs.readFile(vttPath, 'utf-8');
                        const vttKvKey = `vtt:${videoId}:${usedLanguage || 'default'}`;
                        await cacheStore.setValue(vttKvKey, vttContent, { contentType: 'text/vtt' });
                        output.vttKvKey = vttKvKey;
                        output.vttFilename = fname;
                    }

                    await cacheStore.setValue(cacheKey, output);
                    if (usedLanguage && usedLanguage !== requestedLangKey) {
                        await cacheStore.setValue(`yt:${videoId}:${usedLanguage}`, output);
                    }

                    await Actor.pushData(output);
                    return; // success — exit processVideo

                } catch (err) {
                    const msg = err?.message || String(err);
                    const errStderr = err?.stderr || '';

                    if (msg.startsWith('BLOCKED:')) {
                        blockedReason = msg.split(':')[1];
                        lastError = msg;
                        break; // abandon retries for this proxy mode, try next
                    }

                    // Also catch blocking when yt-dlp exits non-zero (HTTP 429 etc.)
                    const detectedBlock = normalizeBlockedReason(errStderr || msg);
                    if (detectedBlock !== 'unknown') {
                        blockedReason = detectedBlock;
                        lastError = msg;
                        break;
                    }

                    lastError = msg;
                    if (debug) log.warning(`Attempt ${attempt + 1}/${Math.max(1, maxRetries)} failed for ${videoId}: ${msg}`);
                }
            }
        }
    } finally {
        // Always clean up temp files — previously leaked on every run
        await fs.rm(tempDir, { recursive: true, force: true }).catch(() => {});
    }

    const errorOutput = {
        status: blockedReason ? 'BLOCKED' : 'NO_TRANSCRIPT',
        reason: blockedReason ? 'Blocked by YouTube' : (lastError || 'No transcripts available'),
        subtitleType: 'none',
        source: 'none',
        requestedLanguage,
        selectedLanguage: null,
        languageFallback: false,
        videoUrl: canonicalUrl,
        videoId,
        cacheHit: false,
        cacheKey,
        proxyAttempted,
    };
    if (blockedReason) errorOutput.blockedReason = blockedReason;
    if (lastError) errorOutput.lastError = lastError;
    if (bestTitle) errorOutput.title = bestTitle;
    if (bestChannelName) errorOutput.channelName = bestChannelName;

    await Actor.pushData(errorOutput);
}

// ─── Main execution ───────────────────────────────────────────────────────────

await Actor.init();

const input = (await Actor.getInput()) || {};
const {
    videoUrl,
    videoUrls,
    preferredLanguage,
    languagePreference,
    outputMode = 'text_only',
    removeBrackets = true,
    joinWith = 'space',
    proxyMode = 'auto',
    timeoutMs: inputTimeoutMs,
    timeoutSecs,
    maxRetries = 2,
    saveVttToKV = false,
    debug = false,
} = input;

const timeoutMs = inputTimeoutMs ?? (typeof timeoutSecs === 'number' ? timeoutSecs * 1000 : 180000);
const languagePrefs = normalizePreferredLanguage(preferredLanguage ?? languagePreference);

// Collect all URLs: videoUrls array takes precedence, videoUrl is the single-URL fallback
const rawUrls = [
    ...(Array.isArray(videoUrls) ? videoUrls : []),
    ...(videoUrl ? [videoUrl] : []),
];
const uniqueUrls = [...new Set(rawUrls.filter(Boolean))];

if (!uniqueUrls.length) {
    log.error('No URLs provided. Set videoUrl or videoUrls in the actor input.');
    await Actor.pushData({ status: 'ERROR', reason: 'No URLs provided in input' });
    await Actor.exit();
}

if (debug) {
    log.info(`Processing ${uniqueUrls.length} URL(s), proxyMode=${proxyMode}`);
    try {
        const { stdout } = await runYtDlp(['--version'], { proxyUrl: null, timeoutMs, debug: false, proxyInjected: false });
        log.info(`yt-dlp version: ${String(stdout || '').trim()}`);
    } catch {
        log.info('yt-dlp version: unknown');
    }
}

const cacheStore = await Actor.openKeyValueStore();
const opts = { cacheStore, outputMode, removeBrackets, joinWith, proxyMode, timeoutMs, maxRetries, saveVttToKV, debug, languagePrefs };

for (const rawUrl of uniqueUrls) {
    await processVideo(rawUrl, opts);
}

await Actor.exit();
